            - 名称：缓存
  用途：actions/cache@v4.2.3
  和：
    # 要缓存和恢复的文件、目录和通配符模式的列表
    小路：
    # 用于恢复和保存缓存的显式密钥
    钥匙：
    # 一个有序的多行字符串，列出了前缀匹配的键，用于在键未发生缓存命中时恢复过时的缓存。注意，在这种情况下，“cache-hit”将返回 false。
    恢复键：#可选
    # 上传过程中用于分割大文件的块大小，以字节为单位
    上传块大小：#可选
    # 启用时可选布尔值，允许 Windows 运行器保存或恢复可以在其他平台上分别恢复或保存的缓存
    enableCrossOsArchive: # 可选，默认为 false
    # 如果未找到缓存条目，则工作流失败
    fail-on-cache-miss: #可选，默认为false
    # 检查给定输入（key、restore-keys）的缓存条目是否存在，无需下载缓存
    lookup-only: # 可选，默认为 false
    # 即使之前的步骤失败，也要运行后续步骤来保存缓存
    save-always: # 可选，默认为 false
          
